# Generated by Django 3.2 on 2022-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_tweetpost_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpost',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweetpost',
            name='schedule_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweetpost',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
