# Generated by Django 3.2 on 2022-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20220314_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpost',
            name='post_done',
            field=models.BooleanField(default=False),
        ),
    ]
