# Generated by Django 3.2 on 2022-04-02 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_tweetpost_post_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
